### PR TITLE
Padding added to column left

### PR DESCRIPTION
**Pull request by ahamza360**
Padding added for better readability.

### CODE REVIEW

**Review by jameesy — CHANGES_REQUESTED** [review]
Hey friend, thanks for the contribution! :)

Don't suppose you can recommit without your linting rules activated?

**Comment by ahamza360** [comment]
I have made the changes with linting off. I am new to making pull requests. Let me know if it is fine. Thanks

**Comment by jameesy** [comment]
Awesome :) thanks very much

**Review by jameesy — COMMENTED** [review]
Merged!

**Pull request merged**
